name: github pages

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment

jobs:
  deploy:
    name: Deploy doc
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Use OCaml
        uses: ocaml/setup-ocaml@v3
        with:
          ocaml-compiler: '5.2'
          dune-cache: true
          allow-prerelease-opam: true

      # temporary until it's in a release
      - run: opam pin picos 0.6.0 -y -n

      - run: opam install odig moonpool trace
      - run: opam pin . -y -n
      - run: opam install . --deps-only
      - run: opam install .

      - run: opam exec -- odig odoc --cache-dir=_doc/ nanoev nanoev-picos nanoev-posix nanoev_tiny_httpd

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_doc/html
          destination_dir: .
          enable_jekyll: false
